version: '3.6'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: nodejs
      POSTGRES_USER: postgres
      POSTGRES_DB: Fintech
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  graphql-engine:
    image: hasura/graphql-engine:v2.0.10
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:nodejs@postgres:5432/Fintech
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: Hii

volumes:
  postgres_data:
